import { Student, Activity, JobOpportunity, AlumniPathway, StudentProfile, RadarDataPoint } from '@/types';

export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'Maria Garcia',
    email: 'maria.garcia@university.edu',
    major: 'Computer Science',
    gpa: 2.8,
    persistenceScore: 45,
    riskLevel: 'high-risk',
    lastEngagement: '2024-01-15',
    autoNudgesSent: 3,
    nextMeeting: '2024-01-25',
    studentId: 'CS-2021-1234',
    attendance: 68,
    assignmentCompletion: 72,
    lmsLogins: 15,
    courses: [
      { code: 'MATH101', name: 'Calculus I', grade: 'D+', trend: 'down', lastSubmission: '2024-01-10' },
      { code: 'CS201', name: 'Data Structures', grade: 'C', trend: 'stable', lastSubmission: '2024-01-12' },
      { code: 'ENG102', name: 'Writing II', grade: 'B-', trend: 'up', lastSubmission: '2024-01-14' },
    ],
    financialHolds: [
      { type: 'Library Fine', amount: 45, deadline: '2024-02-01', status: 'active' },
      { type: 'Lab Fee', amount: 120, deadline: '2024-02-15', status: 'active' },
    ],
    meetingNotes: [
      { date: '2023-12-10', topic: 'Mid-semester check-in', notes: 'Student struggling with Math 101. Recommended tutoring.', advisor: 'Dr. Smith' },
      { date: '2023-11-05', topic: 'Academic planning', notes: 'Discussed course load for spring semester.', advisor: 'Dr. Smith' },
    ],
  },
  {
    id: '2',
    name: 'Alex Johnson',
    email: 'alex.johnson@university.edu',
    major: 'Biology',
    gpa: 3.2,
    persistenceScore: 65,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-20',
    autoNudgesSent: 1,
    nextMeeting: '2024-01-28',
    studentId: 'BIO-2020-5678',
    attendance: 82,
    assignmentCompletion: 85,
    lmsLogins: 28,
    courses: [
      { code: 'BIO301', name: 'Genetics', grade: 'B', trend: 'stable', lastSubmission: '2024-01-18' },
      { code: 'CHEM201', name: 'Organic Chemistry', grade: 'C+', trend: 'down', lastSubmission: '2024-01-16' },
      { code: 'STAT101', name: 'Statistics', grade: 'B+', trend: 'up', lastSubmission: '2024-01-19' },
    ],
    financialHolds: [],
    meetingNotes: [
      { date: '2024-01-08', topic: 'Career planning', notes: 'Interested in medical school. Need to improve chemistry grade.', advisor: 'Dr. Williams' },
    ],
  },
  {
    id: '3',
    name: 'Sarah Chen',
    email: 'sarah.chen@university.edu',
    major: 'Engineering',
    gpa: 3.9,
    persistenceScore: 92,
    riskLevel: 'safe',
    lastEngagement: '2024-01-22',
    autoNudgesSent: 0,
    studentId: 'ENG-2021-9012',
    attendance: 96,
    assignmentCompletion: 98,
    lmsLogins: 42,
    courses: [
      { code: 'ENG401', name: 'Advanced Thermodynamics', grade: 'A', trend: 'stable', lastSubmission: '2024-01-21' },
      { code: 'MATH301', name: 'Differential Equations', grade: 'A-', trend: 'up', lastSubmission: '2024-01-20' },
      { code: 'PHY301', name: 'Quantum Mechanics', grade: 'A', trend: 'stable', lastSubmission: '2024-01-22' },
    ],
    financialHolds: [],
    meetingNotes: [
      { date: '2024-01-15', topic: 'Research opportunities', notes: 'Exploring graduate school options. Strong candidate for fellowships.', advisor: 'Dr. Martinez' },
    ],
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'james.wilson@university.edu',
    major: 'Business',
    gpa: 3.5,
    persistenceScore: 78,
    riskLevel: 'safe',
    lastEngagement: '2024-01-19',
    autoNudgesSent: 0,
    nextMeeting: '2024-02-02',
    studentId: 'BUS-2022-3456',
    attendance: 88,
    assignmentCompletion: 92,
    lmsLogins: 35,
    courses: [
      { code: 'BUS301', name: 'Financial Management', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-17' },
      { code: 'MKT201', name: 'Marketing Principles', grade: 'B+', trend: 'up', lastSubmission: '2024-01-19' },
      { code: 'ECON301', name: 'Microeconomics', grade: 'A', trend: 'up', lastSubmission: '2024-01-18' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '5',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@university.edu',
    major: 'Psychology',
    gpa: 2.9,
    persistenceScore: 58,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-10',
    autoNudgesSent: 2,
    nextMeeting: '2024-01-26',
    studentId: 'PSY-2021-7890',
    attendance: 75,
    assignmentCompletion: 78,
    lmsLogins: 22,
    courses: [
      { code: 'PSY301', name: 'Cognitive Psychology', grade: 'C+', trend: 'down', lastSubmission: '2024-01-08' },
      { code: 'PSY201', name: 'Research Methods', grade: 'B-', trend: 'stable', lastSubmission: '2024-01-09' },
      { code: 'SOC201', name: 'Social Theory', grade: 'C', trend: 'down', lastSubmission: '2024-01-07' },
    ],
    financialHolds: [
      { type: 'Parking Fine', amount: 75, deadline: '2024-01-30', status: 'active' },
    ],
    meetingNotes: [
      { date: '2023-12-15', topic: 'Academic concerns', notes: 'Missing assignments. Need time management strategies.', advisor: 'Dr. Brown' },
    ],
  },
  {
    id: '6',
    name: 'Michael Kim',
    email: 'michael.kim@university.edu',
    major: 'Mathematics',
    gpa: 3.7,
    persistenceScore: 85,
    riskLevel: 'safe',
    lastEngagement: '2024-01-21',
    autoNudgesSent: 0,
    studentId: 'MATH-2020-2345',
    attendance: 94,
    assignmentCompletion: 95,
    lmsLogins: 38,
    courses: [
      { code: 'MATH401', name: 'Abstract Algebra', grade: 'A', trend: 'stable', lastSubmission: '2024-01-20' },
      { code: 'MATH301', name: 'Real Analysis', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-21' },
      { code: 'CS201', name: 'Data Structures', grade: 'B+', trend: 'up', lastSubmission: '2024-01-19' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '7',
    name: 'Jessica Taylor',
    email: 'jessica.taylor@university.edu',
    major: 'English',
    gpa: 3.3,
    persistenceScore: 72,
    riskLevel: 'safe',
    lastEngagement: '2024-01-18',
    autoNudgesSent: 0,
    studentId: 'ENG-2022-6789',
    attendance: 86,
    assignmentCompletion: 89,
    lmsLogins: 30,
    courses: [
      { code: 'ENG301', name: 'Victorian Literature', grade: 'B+', trend: 'stable', lastSubmission: '2024-01-17' },
      { code: 'ENG401', name: 'Creative Writing', grade: 'A-', trend: 'up', lastSubmission: '2024-01-18' },
      { code: 'HIST201', name: 'World History', grade: 'B', trend: 'stable', lastSubmission: '2024-01-16' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '8',
    name: 'David Martinez',
    email: 'david.martinez@university.edu',
    major: 'Computer Science',
    gpa: 2.5,
    persistenceScore: 38,
    riskLevel: 'high-risk',
    lastEngagement: '2024-01-12',
    autoNudgesSent: 4,
    nextMeeting: '2024-01-24',
    studentId: 'CS-2021-4567',
    attendance: 62,
    assignmentCompletion: 65,
    lmsLogins: 12,
    courses: [
      { code: 'CS301', name: 'Algorithms', grade: 'D', trend: 'down', lastSubmission: '2024-01-05' },
      { code: 'CS201', name: 'Data Structures', grade: 'D+', trend: 'down', lastSubmission: '2024-01-08' },
      { code: 'MATH201', name: 'Discrete Math', grade: 'C-', trend: 'stable', lastSubmission: '2024-01-10' },
    ],
    financialHolds: [
      { type: 'Tuition Balance', amount: 850, deadline: '2024-02-01', status: 'active' },
      { type: 'Lab Fee', amount: 95, deadline: '2024-01-28', status: 'active' },
    ],
    meetingNotes: [
      { date: '2023-12-20', topic: 'Academic probation warning', notes: 'Must improve GPA to 2.75 by end of semester.', advisor: 'Dr. Smith' },
    ],
  },
  {
    id: '9',
    name: 'Ashley Brown',
    email: 'ashley.brown@university.edu',
    major: 'Nursing',
    gpa: 3.6,
    persistenceScore: 81,
    riskLevel: 'safe',
    lastEngagement: '2024-01-20',
    autoNudgesSent: 0,
    studentId: 'NUR-2020-8901',
    attendance: 92,
    assignmentCompletion: 94,
    lmsLogins: 36,
    courses: [
      { code: 'NUR301', name: 'Pharmacology', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-19' },
      { code: 'NUR401', name: 'Clinical Practice', grade: 'A', trend: 'up', lastSubmission: '2024-01-20' },
      { code: 'BIO301', name: 'Anatomy', grade: 'B+', trend: 'stable', lastSubmission: '2024-01-18' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '10',
    name: 'Christopher Lee',
    email: 'chris.lee@university.edu',
    major: 'History',
    gpa: 3.1,
    persistenceScore: 68,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-16',
    autoNudgesSent: 1,
    nextMeeting: '2024-01-30',
    studentId: 'HIST-2021-1122',
    attendance: 79,
    assignmentCompletion: 82,
    lmsLogins: 25,
    courses: [
      { code: 'HIST301', name: 'American History', grade: 'B', trend: 'stable', lastSubmission: '2024-01-15' },
      { code: 'HIST401', name: 'Research Seminar', grade: 'C+', trend: 'down', lastSubmission: '2024-01-14' },
      { code: 'POL201', name: 'Political Science', grade: 'B-', trend: 'stable', lastSubmission: '2024-01-16' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '11',
    name: 'Rachel Anderson',
    email: 'rachel.anderson@university.edu',
    major: 'Chemistry',
    gpa: 3.8,
    persistenceScore: 88,
    riskLevel: 'safe',
    lastEngagement: '2024-01-22',
    autoNudgesSent: 0,
    studentId: 'CHEM-2020-3344',
    attendance: 95,
    assignmentCompletion: 97,
    lmsLogins: 40,
    courses: [
      { code: 'CHEM401', name: 'Physical Chemistry', grade: 'A', trend: 'stable', lastSubmission: '2024-01-21' },
      { code: 'CHEM301', name: 'Inorganic Chemistry', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-22' },
      { code: 'MATH301', name: 'Calculus III', grade: 'A', trend: 'up', lastSubmission: '2024-01-20' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '12',
    name: 'Daniel Thompson',
    email: 'daniel.thompson@university.edu',
    major: 'Economics',
    gpa: 2.7,
    persistenceScore: 52,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-14',
    autoNudgesSent: 2,
    nextMeeting: '2024-01-27',
    studentId: 'ECON-2022-5566',
    attendance: 73,
    assignmentCompletion: 76,
    lmsLogins: 20,
    courses: [
      { code: 'ECON301', name: 'Macroeconomics', grade: 'C', trend: 'down', lastSubmission: '2024-01-11' },
      { code: 'ECON201', name: 'Econometrics', grade: 'C+', trend: 'stable', lastSubmission: '2024-01-13' },
      { code: 'MATH201', name: 'Statistics', grade: 'B-', trend: 'up', lastSubmission: '2024-01-14' },
    ],
    financialHolds: [
      { type: 'Book Store', amount: 125, deadline: '2024-02-10', status: 'active' },
    ],
    meetingNotes: [],
  },
  {
    id: '13',
    name: 'Sophia Nguyen',
    email: 'sophia.nguyen@university.edu',
    major: 'Art',
    gpa: 3.4,
    persistenceScore: 75,
    riskLevel: 'safe',
    lastEngagement: '2024-01-19',
    autoNudgesSent: 0,
    studentId: 'ART-2021-7788',
    attendance: 87,
    assignmentCompletion: 90,
    lmsLogins: 32,
    courses: [
      { code: 'ART301', name: 'Studio Art', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-18' },
      { code: 'ART401', name: 'Art History', grade: 'B+', trend: 'up', lastSubmission: '2024-01-19' },
      { code: 'DES201', name: 'Graphic Design', grade: 'A', trend: 'stable', lastSubmission: '2024-01-17' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '14',
    name: 'Ryan White',
    email: 'ryan.white@university.edu',
    major: 'Physics',
    gpa: 3.0,
    persistenceScore: 63,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-17',
    autoNudgesSent: 1,
    nextMeeting: '2024-01-29',
    studentId: 'PHY-2021-9900',
    attendance: 80,
    assignmentCompletion: 83,
    lmsLogins: 27,
    courses: [
      { code: 'PHY301', name: 'Classical Mechanics', grade: 'B-', trend: 'down', lastSubmission: '2024-01-15' },
      { code: 'PHY201', name: 'Electromagnetism', grade: 'C+', trend: 'stable', lastSubmission: '2024-01-17' },
      { code: 'MATH301', name: 'Linear Algebra', grade: 'B', trend: 'stable', lastSubmission: '2024-01-16' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '15',
    name: 'Olivia Harris',
    email: 'olivia.harris@university.edu',
    major: 'Sociology',
    gpa: 3.5,
    persistenceScore: 79,
    riskLevel: 'safe',
    lastEngagement: '2024-01-21',
    autoNudgesSent: 0,
    studentId: 'SOC-2020-1234',
    attendance: 89,
    assignmentCompletion: 91,
    lmsLogins: 34,
    courses: [
      { code: 'SOC301', name: 'Social Research', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-20' },
      { code: 'SOC401', name: 'Urban Sociology', grade: 'B+', trend: 'up', lastSubmission: '2024-01-21' },
      { code: 'PSY201', name: 'Social Psychology', grade: 'A', trend: 'stable', lastSubmission: '2024-01-19' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '16',
    name: 'Brandon Clark',
    email: 'brandon.clark@university.edu',
    major: 'Political Science',
    gpa: 2.6,
    persistenceScore: 48,
    riskLevel: 'high-risk',
    lastEngagement: '2024-01-11',
    autoNudgesSent: 3,
    nextMeeting: '2024-01-25',
    studentId: 'POL-2022-5678',
    attendance: 67,
    assignmentCompletion: 70,
    lmsLogins: 16,
    courses: [
      { code: 'POL301', name: 'Comparative Politics', grade: 'D+', trend: 'down', lastSubmission: '2024-01-06' },
      { code: 'POL201', name: 'International Relations', grade: 'C-', trend: 'down', lastSubmission: '2024-01-09' },
      { code: 'HIST201', name: 'Modern History', grade: 'C', trend: 'stable', lastSubmission: '2024-01-11' },
    ],
    financialHolds: [
      { type: 'Student Activities Fee', amount: 200, deadline: '2024-02-05', status: 'active' },
    ],
    meetingNotes: [
      { date: '2023-12-18', topic: 'Academic warning', notes: 'Need to improve attendance and assignment submission.', advisor: 'Dr. Johnson' },
    ],
  },
  {
    id: '17',
    name: 'Lauren Scott',
    email: 'lauren.scott@university.edu',
    major: 'Environmental Science',
    gpa: 3.6,
    persistenceScore: 82,
    riskLevel: 'safe',
    lastEngagement: '2024-01-20',
    autoNudgesSent: 0,
    studentId: 'ENV-2021-9012',
    attendance: 91,
    assignmentCompletion: 93,
    lmsLogins: 37,
    courses: [
      { code: 'ENV301', name: 'Ecology', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-19' },
      { code: 'ENV401', name: 'Climate Science', grade: 'A', trend: 'up', lastSubmission: '2024-01-20' },
      { code: 'BIO301', name: 'Biology', grade: 'B+', trend: 'stable', lastSubmission: '2024-01-18' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '18',
    name: 'Kevin Adams',
    email: 'kevin.adams@university.edu',
    major: 'Music',
    gpa: 3.2,
    persistenceScore: 70,
    riskLevel: 'safe',
    lastEngagement: '2024-01-18',
    autoNudgesSent: 0,
    studentId: 'MUS-2020-3456',
    attendance: 85,
    assignmentCompletion: 87,
    lmsLogins: 29,
    courses: [
      { code: 'MUS301', name: 'Music Theory', grade: 'B+', trend: 'stable', lastSubmission: '2024-01-17' },
      { code: 'MUS401', name: 'Performance', grade: 'A-', trend: 'up', lastSubmission: '2024-01-18' },
      { code: 'HIST201', name: 'Music History', grade: 'B', trend: 'stable', lastSubmission: '2024-01-16' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
  {
    id: '19',
    name: 'Madison Turner',
    email: 'madison.turner@university.edu',
    major: 'Biology',
    gpa: 2.8,
    persistenceScore: 55,
    riskLevel: 'at-risk',
    lastEngagement: '2024-01-13',
    autoNudgesSent: 2,
    nextMeeting: '2024-01-26',
    studentId: 'BIO-2022-7890',
    attendance: 76,
    assignmentCompletion: 79,
    lmsLogins: 23,
    courses: [
      { code: 'BIO301', name: 'Cell Biology', grade: 'C+', trend: 'down', lastSubmission: '2024-01-10' },
      { code: 'BIO201', name: 'Microbiology', grade: 'C', trend: 'stable', lastSubmission: '2024-01-12' },
      { code: 'CHEM201', name: 'Organic Chemistry', grade: 'B-', trend: 'up', lastSubmission: '2024-01-13' },
    ],
    financialHolds: [
      { type: 'Lab Damage', amount: 65, deadline: '2024-02-08', status: 'active' },
    ],
    meetingNotes: [],
  },
  {
    id: '20',
    name: 'Tyler Walker',
    email: 'tyler.walker@university.edu',
    major: 'Philosophy',
    gpa: 3.7,
    persistenceScore: 84,
    riskLevel: 'safe',
    lastEngagement: '2024-01-21',
    autoNudgesSent: 0,
    studentId: 'PHIL-2021-2345',
    attendance: 93,
    assignmentCompletion: 95,
    lmsLogins: 39,
    courses: [
      { code: 'PHIL301', name: 'Ethics', grade: 'A', trend: 'stable', lastSubmission: '2024-01-20' },
      { code: 'PHIL401', name: 'Metaphysics', grade: 'A-', trend: 'stable', lastSubmission: '2024-01-21' },
      { code: 'ENG201', name: 'Critical Thinking', grade: 'A', trend: 'up', lastSubmission: '2024-01-19' },
    ],
    financialHolds: [],
    meetingNotes: [],
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    message: 'AI sent SMS nudge to Maria Garcia about Math 101 tutoring',
    timestamp: '5 min ago',
    type: 'nudge',
  },
  {
    id: '2',
    message: 'Alex Johnson booked advising session',
    timestamp: '12 min ago',
    type: 'booking',
  },
  {
    id: '3',
    message: 'System detected drop in David Martinez attendance',
    timestamp: '28 min ago',
    type: 'alert',
  },
  {
    id: '4',
    message: 'Emily Rodriguez completed career assessment',
    timestamp: '45 min ago',
    type: 'meeting',
  },
  {
    id: '5',
    message: 'AI sent email reminder to Brandon Clark about financial hold',
    timestamp: '1 hour ago',
    type: 'nudge',
  },
  {
    id: '6',
    message: 'Sarah Chen submitted research proposal',
    timestamp: '2 hours ago',
    type: 'meeting',
  },
  {
    id: '7',
    message: 'System flagged Madison Turner for GPA monitoring',
    timestamp: '3 hours ago',
    type: 'alert',
  },
  {
    id: '8',
    message: 'Christopher Lee rescheduled advising appointment',
    timestamp: '4 hours ago',
    type: 'booking',
  },
  {
    id: '9',
    message: 'AI sent course registration reminder to 15 students',
    timestamp: '5 hours ago',
    type: 'nudge',
  },
  {
    id: '10',
    message: 'Daniel Thompson completed time management workshop',
    timestamp: '6 hours ago',
    type: 'meeting',
  },
];

export const mockStudentProfile: StudentProfile = {
  name: 'Jordan Smith',
  major: 'Computer Science',
  creditsEarned: 90,
  totalCredits: 120,
  careerReadinessScore: 78,
  skills: [
    { name: 'Python', proficiency: 'Advanced', category: 'Technical', acquiredFrom: ['CS201', 'CS301', 'CS401'] },
    { name: 'Data Structures', proficiency: 'Intermediate', category: 'Technical', acquiredFrom: ['CS201', 'CS202'] },
    { name: 'Machine Learning', proficiency: 'Beginner', category: 'Technical', acquiredFrom: ['CS401'] },
    { name: 'JavaScript', proficiency: 'Intermediate', category: 'Technical', acquiredFrom: ['CS250', 'CS350'] },
    { name: 'Communication', proficiency: 'Advanced', category: 'Soft Skills', acquiredFrom: ['ENG201', 'COM101'] },
    { name: 'Problem Solving', proficiency: 'Advanced', category: 'Soft Skills', acquiredFrom: ['Multiple courses'] },
    { name: 'Team Collaboration', proficiency: 'Intermediate', category: 'Soft Skills', acquiredFrom: ['CS301', 'BUS201'] },
    { name: 'Data Visualization', proficiency: 'Beginner', category: 'Technical', acquiredFrom: ['STAT201'] },
    { name: 'SQL', proficiency: 'Intermediate', category: 'Technical', acquiredFrom: ['CS250', 'CS260'] },
    { name: 'Agile Methodology', proficiency: 'Beginner', category: 'Domain Knowledge', acquiredFrom: ['CS350'] },
    { name: 'Web Development', proficiency: 'Intermediate', category: 'Technical', acquiredFrom: ['CS250', 'CS350'] },
    { name: 'Critical Thinking', proficiency: 'Advanced', category: 'Soft Skills', acquiredFrom: ['PHIL101', 'Multiple courses'] },
  ],
  completedCourses: [
    'CS101', 'CS102', 'CS201', 'CS202', 'CS250', 'CS301', 'CS350', 'CS401',
    'MATH101', 'MATH201', 'STAT201', 'ENG101', 'ENG201', 'COM101', 'BUS201', 'PHIL101'
  ],
};

export const mockJobOpportunities: JobOpportunity[] = [
  {
    id: '1',
    company: 'Tech Innovations Inc',
    title: 'Junior Software Engineer',
    matchPercentage: 85,
    requiredSkills: ['Python', 'Data Structures', 'SQL', 'Web Development', 'Team Collaboration'],
    skillGaps: ['Machine Learning'],
    salary: '$75,000 - $90,000',
    location: 'San Francisco, CA',
    deadline: '2024-02-15',
  },
  {
    id: '2',
    company: 'Data Solutions Corp',
    title: 'Data Analyst Intern',
    matchPercentage: 72,
    requiredSkills: ['Python', 'SQL', 'Data Visualization', 'Statistics', 'Communication'],
    skillGaps: ['Data Visualization', 'Advanced Statistics'],
    salary: '$25/hour',
    location: 'Remote',
    deadline: '2024-02-28',
  },
  {
    id: '3',
    company: 'StartupHub',
    title: 'Full Stack Developer',
    matchPercentage: 68,
    requiredSkills: ['JavaScript', 'Web Development', 'SQL', 'Agile', 'Problem Solving'],
    skillGaps: ['React', 'Node.js', 'Advanced Agile'],
    salary: '$70,000 - $85,000',
    location: 'Austin, TX',
    deadline: '2024-03-10',
  },
  {
    id: '4',
    company: 'AI Research Labs',
    title: 'Machine Learning Intern',
    matchPercentage: 58,
    requiredSkills: ['Python', 'Machine Learning', 'Data Structures', 'Statistics', 'Research'],
    skillGaps: ['Advanced ML', 'Deep Learning', 'TensorFlow'],
    salary: '$30/hour',
    location: 'Boston, MA',
    deadline: '2024-02-20',
  },
  {
    id: '5',
    company: 'CloudTech Systems',
    title: 'DevOps Engineer',
    matchPercentage: 55,
    requiredSkills: ['Python', 'Linux', 'AWS', 'Docker', 'CI/CD'],
    skillGaps: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    salary: '$80,000 - $95,000',
    location: 'Seattle, WA',
    deadline: '2024-03-01',
  },
];

export const mockAlumniPathways: AlumniPathway[] = [
  {
    id: '1',
    name: 'Alumnus A',
    startingMajor: 'English',
    currentRole: 'UX Content Strategist at Google',
    careerTransitions: ['Content Writer', 'UX Writer', 'Senior UX Writer', 'Content Strategist'],
    keySkills: ['Writing', 'User Research', 'Information Architecture', 'Psychology', 'Design Thinking'],
    courses: ['ENG301 - Technical Writing', 'PSY201 - Cognitive Psychology', 'CS101 - Intro to Web'],
    timeline: '2016-2024 (8 years)',
  },
  {
    id: '2',
    name: 'Alumnus B',
    startingMajor: 'History',
    currentRole: 'Product Manager at Microsoft',
    careerTransitions: ['Research Assistant', 'Business Analyst', 'Associate PM', 'Product Manager'],
    keySkills: ['Research', 'Data Analysis', 'Communication', 'Strategy', 'Agile'],
    courses: ['HIST301 - Research Methods', 'BUS201 - Business Analytics', 'CS201 - Data Structures'],
    timeline: '2015-2023 (8 years)',
  },
  {
    id: '3',
    name: 'Alumnus C',
    startingMajor: 'Biology',
    currentRole: 'Data Scientist at Pfizer',
    careerTransitions: ['Lab Technician', 'Bioinformatics Analyst', 'Data Analyst', 'Data Scientist'],
    keySkills: ['Biology', 'Statistics', 'Python', 'Machine Learning', 'Data Visualization'],
    courses: ['BIO401 - Bioinformatics', 'STAT301 - Advanced Statistics', 'CS401 - Machine Learning'],
    timeline: '2014-2022 (8 years)',
  },
  {
    id: '4',
    name: 'Alumnus D',
    startingMajor: 'Computer Science',
    currentRole: 'Tech Lead at Amazon',
    careerTransitions: ['Software Engineer', 'Senior Engineer', 'Engineering Manager', 'Tech Lead'],
    keySkills: ['Software Engineering', 'Architecture', 'Leadership', 'Cloud Computing', 'Distributed Systems'],
    courses: ['CS401 - Advanced Algorithms', 'CS450 - Cloud Computing', 'BUS301 - Leadership'],
    timeline: '2013-2024 (11 years)',
  },
];

export const mockRadarData: RadarDataPoint[] = [
  { skill: 'Python', student: 90, target: 85 },
  { skill: 'Statistics', student: 60, target: 80 },
  { skill: 'Communication', student: 95, target: 75 },
  { skill: 'Data Viz', student: 40, target: 70 },
  { skill: 'Machine Learning', student: 45, target: 85 },
  { skill: 'Problem Solving', student: 85, target: 80 },
];
